# Source: application-deploy/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: bigfish-kyrgyzstan-ru
  namespace: game-platform-kg
  labels:
    app: bigfish-kyrgyzstan-ru
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: bigfish-kyrgyzstan-ru
---
# Source: application-deploy/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigfish-kyrgyzstan-ru
  namespace: game-platform-kg
  labels:
    app: bigfish-kyrgyzstan-ru
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  selector:
    matchLabels:
      app: bigfish-kyrgyzstan-ru
  template:
    metadata:
      labels:
        app: bigfish-kyrgyzstan-ru
    spec:
      imagePullSecrets:
      - name: docker-registry-pull
      containers:
      - name: bigfish-kyrgyzstan-ru
        image: "harbor-game.beeline.kg/web-view-games/bigfish-kyrgyzstan-ru:main-1233906"
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: 1024Mi
          requests:
            memory: 700Mi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - bigfish-kyrgyzstan-ru
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 100
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - bigfish-kyrgyzstan-ru
            topologyKey: kubernetes.io/hostname