apiVersion: v1
data:
  default.conf: |
    log_format gpl '$time_iso8601 | $request, $status, $body_bytes_sent bytes |
    $remote_addr => $host => $proxy_host ($upstream_addr) | $upstream_status,
    $upstream_response_time sec, $upstream_response_length bytes | agent
    "$http_user_agent" $http_upgrade';


      map $lang $target_jewel_match {
        kg      http://jewel-match-kyrgyzstan.game-platform-kg.svc.cluster.local:8080;
        default http://jewel-match-kyrgyzstan-ru.game-platform-kg.svc.cluster.local:8080;
      }

      map $arg_lang $target_bigfish {
        kg      http://bigfish-kyrgyzstan.game-platform-kg.svc.cluster.local:8080;
        default http://bigfish-kyrgyzstan-ru.game-platform-kg.svc.cluster.local:8080;

      }

      map $arg_lang $target_baige3d {
        kg      http://baige3d-kyrgyzstan.game-platform-kg.svc.cluster.local:8080;
        default http://baige3d-kyrgyzstan-ru.game-platform-kg.svc.cluster.local:8080;

      }

      server {
          listen         8080;
          server_name    localhost;
          error_page     500 502 503 504  /50x.html;
          access_log     /var/log/nginx/gp.access.log  gpl;
          server_tokens  off;
          add_header     Strict-Transport-Security "max-age=3600; includeSubDomains" always;
          add_header     X-Content-Type-Options "nosniff";
          add_header     X-XSS-Protection "1; mode=block";
          resolver       172.28.2.2 valid=10s;


          location = /50x.html {
              root   /usr/share/nginx/html;
          }

          ### GAMES ###########################
          location /play/ {
              add_header X-Frame-Options "SAMEORIGIN";

              ##### casual games ### START ###########
              location /play/onetfruitclassic/ { proxy_pass http://game-onetfruitclassic.game-platform-kg.svc.cluster.local:8080/; }
              location /play/sumosaga/ { proxy_pass http://game-sumosaga.game-platform-kg.svc.cluster.local:8080; }
              location /play/hexa-merge/ { proxy_pass http://game-hexa-merge.game-platform-kg.svc.cluster.local:8080/; }
              location /play/zoomerge/ { proxy_pass http://game-zoomerge.game-platform-kg.svc.cluster.local:8080/; }
              location /play/crossychicken/ { proxy_pass http://game-crossychicken.game-platform-kg.svc.cluster.local:8080/; }
              location /play/marbles/ { proxy_pass http://game-marbles.game-platform-kg.svc.cluster.local:8080/; }
              location /play/racing/ { proxy_pass http://racing-kg.game-platform-kg.svc.cluster.local:8080/; }

              location /play/jewel-match/ {

                set $lang ru;
                set $target_url http://jewel-match-kyrgyzstan-ru.game-platform-kg.svc.cluster.local:8080;

                if ($args ~ "(^|&)lang=kg(&|$)") {
                    set $lang kg;
                    set $target_url http://jewel-match-kyrgyzstan.game-platform-kg.svc.cluster.local:8080;
                }

                rewrite ^/play/jewel-match/(.*)$ /$1 break;
                add_header X-Custom-Header $lang;
                add_header X-Custom-Header_2 $target_url;
                proxy_pass $target_url;
              }

              location /play/bigfish/ {
                rewrite ^/play/bigfish/(.*)$ /$1 break;
                proxy_pass $target_bigfish;
              }

              location /play/baige3d/ {
                rewrite ^/play/baige3d/(.*)$ /$1 break;
                proxy_pass $target_baige3d;

              }

              ##### casual games ### END #############
          }

          ##### roulette2024 #### START ##########
          # location /play/roulette2024 {
          #     location /play/roulette2024/api/ { proxy_pass http://platform-backend.game-platform-kg.svc.cluster.local:8080/api/; }
          #     location /play/roulette2024 {
          #       proxy_pass https://kyrgyzstan-roulette-v3.k8s-dev.beeline.kz/;
          #       add_header Content-Security-Policy "*";
          #     }
          # }
          ##### roulette2024 ##### END ###########

          ##### game-platform ###### START ##########
          # location /wofscript/ {
          #     proxy_pass http://wofscript.game-platform-kg.svc.cluster.local:8080/;
          # }

            location /sdk/ {
                proxy_pass http://sdk.game-platform-kg.svc.cluster.local:8080/;
            }

            # location /admin/ {
            #     proxy_pass http://admin.game-platform-kg.svc.cluster.local:8080/;
            # }

            # location /admin/api/ {
            #     proxy_pass http://backend.game-platform-kg.svc.cluster.local:8080/api/;
            # }

            location /api/ {
                proxy_pass http://backend.game-platform-kg.svc.cluster.local:8080/api/;
            }

            # location /quiz-admin/api/ {
            #     proxy_pass http://admin-quizzes.game-platform-kg.svc.cluster.local:8080/quiz-admin/;
            # }

            location / {
                include /etc/nginx/lock;
                proxy_pass http://frontend.game-platform-kg.svc.cluster.local:8080/;
            }
            ##### game-platform ###### END ############

        }
kind: ConfigMap
metadata:
  name: gateway
  namespace: game-platform-kg