apiVersion: v1
data:
  default.conf: |
    log_format gpl '$time_iso8601 | $request, $status, $body_bytes_sent bytes |
    $remote_addr => $host => $proxy_host ($upstream_addr) | $upstream_status,
    $upstream_response_time sec, $upstream_response_length bytes | agent
    "$http_user_agent" $http_upgrade';

      server {
          listen         8080;
          server_name    localhost;
          error_page     500 502 503 504  /50x.html;
          access_log     /var/log/nginx/gp.access.log  gpl;
          server_tokens  off;
          add_header     Strict-Transport-Security "max-age=3600; includeSubDomains" always;
          add_header     X-Content-Type-Options "nosniff";
          add_header     X-XSS-Protection "1; mode=block";
     
     
          location = /50x.html {
              root   /usr/share/nginx/html;
          }
     
          ### GAMES ###########################
          location /play/ {
              add_header X-Frame-Options "SAMEORIGIN";
     
              ##### casual games ### START ###########
              location /play/onetfruitclassic/ { proxy_pass http://game-onetfruitclassic.game-platform-kg.svc.cluster.local:8080/; }
              location /play/sumosaga/ { proxy_pass http://game-sumosaga.game-platform-kg.svc.cluster.local:8080/; }
              location /play/hexa-merge/ { proxy_pass http://game-hexa-merge.game-platform-kg.svc.cluster.local:8080/; }
              location /play/zoomerge/ { proxy_pass http://game-zoomerge.game-platform-kg.svc.cluster.local:8080/; }
              location /play/crossychicken/ { proxy_pass http://game-crossychicken.game-platform-kg.svc.cluster.local:8080/; }
              location /play/marbles/ { proxy_pass http://game-marbles.game-platform-kg.svc.cluster.local:8080/; }
              location /play/racing/ { proxy_pass http://racing-kg.game-platform-kg.svc.cluster.local:8080/; }
              location /play/jewel-match/ru/ { proxy_pass http://jewel-match-kyrgyzstan-ru.game-platform-kg.svc.cluster.local:8080/; }
              location /play/jewel-match/kg/ { proxy_pass http://jewel-match-kyrgyzstan.game-platform-kg.svc.cluster.local:8080/; }
              location /play/bigfish/ru/ { proxy_pass http://bigfish-kyrgyzstan-ru.game-platform-kg.svc.cluster.local:8080/; }
              location /play/bigfish/kg/ { proxy_pass http://bigfish-kyrgyzstan.game-platform-kg.svc.cluster.local:8080/; }
              location /play/baige3d/ru/ { proxy_pass http://baige3d-kyrgyzstan-ru.game-platform-kg.svc.cluster.local:8080/; }
              location /play/baige3d/kg/ { proxy_pass http://baige3d-kyrgyzstan.game-platform-kg.svc.cluster.local:8080/; }
              ##### casual games ### END #############
          }
     
          ##### roulette2024 #### START ##########
          # location /play/roulette2024 {
          #     location /play/roulette2024/api/ { proxy_pass http://kyrgyzstan-game-platform-backend.game-platform-kg.svc.cluster.local/api/; }
          #     location /play/roulette2024 { 
          #       proxy_pass https://kyrgyzstan-roulette-v3.k8s-dev.beeline.kz/;
          #       add_header Content-Security-Policy "*";
          #     }
          # }
          ##### roulette2024 ##### END ###########
     
          ##### game-platform ###### START ##########
          # location /wofscript/ {
          #     proxy_pass http://wofscript.game-platform-kg.svc.cluster.local/;
          # }
     
            location /sdk/ { 
                proxy_pass http://sdk.game-platform-kg.svc.cluster.local:8080/;
            }
     
            location /api/ { 
                proxy_pass http://backend.game-platform-kg.svc.cluster.local:8080/api/;
            }
     
            # location /quiz-admin/api/ { 
            #     proxy_pass http://admin-quizzes.game-platform-kg.svc.cluster.local/quiz-admin/; 
            # }
     
            location / { 
                include /etc/nginx/lock;
                proxy_pass http://frontend.game-platform-kg.svc.cluster.local:8080/; 
            }
            ##### game-platform ###### END ############
     
        }
kind: ConfigMap
metadata:
  name: gateway
  namespace: game-platform-kg