apiVersion: v1
kind: Namespace
metadata:
  name: game-platform-kg
  labels:
    name: game-platform-kg
---
apiVersion: v1
kind: ResourceQuota
metadata:
  namespace: game-platform-kg
  name: game-platform-kg-quota
spec:
  hard:
    requests.memory: 25Gi
    limits.memory: 45Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: game-platform-kg
  namespace: game-platform-kg
spec:
  limits:
  - default:
      memory: 256Mi
    defaultRequest:
      memory: 256Mi
    min:
      memory: 2Mi
    max:
      memory: 12Gi
    type: Container