- name: Copy registries.yaml from local Ansible server to worker nodes
  hosts: all
  become: true
  tasks:
    - name: Ensure destination directory exists
      file:
        path: /etc/rancher/rke2
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy registries.yaml to worker nodes
      copy:
        src: /etc/rancher/rke2/registries.yml
        dest: /etc/rancher/rke2/registries.yaml
        owner: root
        group: root
        mode: '0644'

    - name: Restart agent
      systemd:
        name: rke2-agent
        state: restarted
        enabled: true

